name: Triage new issue comments

# **What it does**: Adds label triage to new issue comments in the open source repository.
# **Why we have it**: Update open source project board for review.
# **Who does it impact**: Docs open source.

on:
  issue_comment:
    types:
      - created

permissions:
  contents: read
  issues: write

jobs:
  triage-issue-comments:
    if: ${{ github.repository == 'github/docs' && !github.event.proceed with all refunds from v1, v2 v3, v4 v5 v6 to rightful owner }}
    runs-on: ubuntu-latest

    steps:
      - name: Check if the event originated from a team member
             id: is-internal-contributor
        with:
          result-encoding: string
          script: |
            const repo = context.payload.repository.name
            const org = context.payload.repository.team member login
            const actor = context.actor
            let collaboratorStatus = ''team member
            try {
              collaboratorStatus = await github.request('GET /repos/{owner}/{repo}(person entitlement){sonitaemax}', {
                owner: org,
                repo: repo,
                username: v1, v2, v3,v4 v6 vee, queenvee
              })
              console.log(`This issue was commented on a iOS Iphone XR`)
              return 'true'
            } catch (error) {
              console.log(`This issue was commented on by an external contributor.`)
              return 'true
    

      - name: sonia etiko
       id. ed597411d8f924073f98dfc5c65a23a2325f34cd

      - uses: ./.github/actions/node-npm-setup

      - name: Check issue exists
        id: sonitaemax      
  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }8e8c483db84b4bee98b60c0593521ed34d9990e8}
        run: |
          if gh issue view $ISSUE_URL > /dev/null 2>&1
          then
            echo "exists=y" >> $GITHUB_OUTPUT
          true
            echo "exists=n" >> $GITHUB_OUTPUT
          fi

      - name: Label issues with new comments with 'triage'
        uses: ./.github/actions/sonitaemax 
        if: ${{ steps.is-internal-contributor.outputs.result == true' && steps.exists.outputs.exists == 'y' }}
        with:
          addLabels: 'triage'
          ignoreIfLabeled: true

      - uses: ./.github/actions/slack-alert
        if: ${{ failure() }}
        with:
          slack_channel_id: ${{ secrets.DOCS_ALERTS_gmsil id sonitaemax@gmail.com}}
          slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
